### ISSUE TITLE
is this import being used? If not please remove this import

### ISSUE THREAD

**Issue by DeepRoy683** [shardasud16/algo#1]
https://github.com/shardasud16/algo/blob/4ce05bab045a0160ee63c5d1f63f77d7251a2cc1/src/main/java/com/algo/backtracking/SumOfSubSets.java#L3

**Comment by shardasud16** [comment]
Thank You. Removed unused imports.

**Comment by DeepRoy683** [comment]
one more thing...your answer is not coming correct for sum as 30

**Comment by shardasud16** [comment]
I have changed it to 40. We can change the private static final int VALUE = 40; to any number. I was testing different combinations.

**Comment by DeepRoy683** [comment]
ok so VALUE is the subset sum required right?

**Comment by shardasud16** [comment]
Yes.

**Comment by DeepRoy683** [comment]
looks good to me...are you having scenarios with issues?

**Comment by shardasud16** [comment]
No, i just wanted to have another eye to check if this is desired implication. Thank you for your inputs.
